### ISSUE TITLE
Migrate to BagIt 5.x

### ISSUE THREAD

**Issue by rvanheest** [DANS-KNAW/easy-split-multi-deposit#13]
As [BagIt](https://github.com/LibraryOfCongress/bagit-java) is refactoring its code base and given some bugs in the 4.x versions, we should migrate to the 5.x version of this library.

We currently solve some bugs in 4.x ourselves in [`AddBagToDeposit`](https://github.com/rvanheest/easy-split-multi-deposit/blob/development/src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddBagToDeposit.scala#L67). This works for now as a hack fix, but moving on to version 5.x is more desirable in the long term.

See also [BagIt issue 35](https://github.com/LibraryOfCongress/bagit-java/issues/35) for an example of how to use the 5.x version and [BagIt issue 36](https://github.com/LibraryOfCongress/bagit-java/issues/36) for the bug we fixed in our code.

As discussed with @janvanmansum, this does not have an urgent priority. We can pick this up if there is some time left at the end of this sprint or in the next sprint.

**Comment by johnscancella** [comment]
you can also look at https://github.com/LibraryOfCongress/bagit-java#examples for more examples

**Comment by lindareijnhoudt** [comment]
EASY-1013
