### ISSUE TITLE
Verify instructions.csv in the preconditions

### ISSUE THREAD

**Issue by rvanheest** [DANS-KNAW/easy-split-multi-deposit#15]
To minimize failure in the `Action.run()` calls, we should perform some validation on the `instructions.csv` file during the `Action.checkPreconditions` phase. This way we fail faster.

Things to validate:
* files that are mentioned in the `instructions.csv` file should exist in the `multi-deposit-directory`
* ...

[feel free to add stuff in the listing above]

**Comment by lindareijnhoudt** [comment]
and vice versa? so files in the `multi-deposit-dir` should also be mentioned in the csv file?

**Comment by rvanheest** [comment]
not sure about that one. I'd say probably yes, but not entirely sure about this. After all, it doesn't hurt the application if some files are in the multideposit directory and then not being mentioned in the `instructions.csv` file or used in the process of converting to a bag or sending to Springfield.

Maybe we should discuss this specific thing a bit more? Is there something stated about this in the specifications? Keep in mind that every validation takes time! We should not validate for things that are not relevant. This is especially true with large multideposits...

**Comment by janvanmansum** [comment]
Not all files need to be specified in the `MDI` (Multi-Deposit Instructions) file, that is the reason for the default file handling. The files about which nothing is specified are processed according to the default file handling rules, for individual files the default can be overriden.

**Comment by rvanheest** [comment]
Note that this is something that is not yet implemented! This is part of the [non-default file handling](https://github.com/DANS-KNAW/easy-split-multi-deposit/blob/master/multi-deposit-instructions.md#non-default-processing), right?

**Comment by lindareijnhoudt** [comment]
EASY-1015
