### ISSUE TITLE
Make this application fully reactive

### ISSUE THREAD

**Issue by rvanheest** [DANS-KNAW/easy-split-multi-deposit#16]
Currently the whole `instructions.csv` file is read into memory before any processing is done. All data is present until the end of the application's execution. However, the data is processed sequentially and only a few fields of some of the datasets are required in the final `Action` (which technically does a `fold` on these fields from all datasets for which these fields are defined). 

We could make this process more reactive by:
* reading the `instructions.csv` file per dataset and then perform the actions on it before reading the next dataset.
* if possible we could execute this in parallel as well by using a `Scheduler`.
* filter out only the datasets and fields required for the final (fold) `Action` and let GC clean up the rest of the data in memory.

The first point requires some more thinking, as we want to collect the failures from all datasets before rolling back and reporting the errors.

The third point should be a fairly straightforward refactoring of mapping a `Dataset` to an instance of a case class and folding over these instances.

**Comment by lindareijnhoudt** [comment]
EASY-1016
