### ISSUE TITLE
Currently ignored csv columns

### ISSUE THREAD

**Issue by rvanheest** [DANS-KNAW/easy-split-multi-deposit#17]
The columns below, that may or may not be in `instructions.csv` file, are currently ignored in the creation of the bags. Before taking this project in production this should be fixed to avoid later problems with '*discarded data*'.

We first need to discuss what to do with them, where to put them in `metadata.xml` (assuming they have to be put in there...) and in which format they have to be put in. I haven't seen consistent examples using these yet.

The following columns are discarded for now:
* `DCX_SPATIAL_SCHEME`
* `DCX_SPATIAL_X`
* `DCX_SPATIAL_Y`
* `DCX_SPATIAL_NORTH`
* `DCX_SPATIAL_SOUTH`
* `DCX_SPATIAL_EAST`
* `DCX_SPATIAL_WEST`
* `DCX_RELATION_QUALIFIER`
* `DCX_RELATION_TITLE`
* `DCX_RELATION_LINK`

**Comment by lindareijnhoudt** [comment]
EASY-1017
