### ISSUE TITLE
Simplify Main

### ISSUE THREAD

**Issue by rvanheest** [DANS-KNAW/easy-split-multi-deposit#18]
Currently `Main.scala` is set up fairly robustly (inherited from the previous version of this project) to take into account future `Action`s that work on the `FileParameters` level. Due to (potential future) pattern matching on `FileParameters` the return type of `getActions(FileParameters)` is `Try[Observable[T]]`, causing `getFileActions` and `getDatasetActions` to have the type `Observable[Try[T]]` and `getActions(Observable[(DatasetID, Dataset)])(Settings)` to be overly complex in its implementation.

The pattern matching on `FileParameters` may be needed in the future (as it was in the previous version of this project), but is not used right now. If it turns out that this pattern matching will not be needed at all, we should simplify this whole maze of types, making it all easier to read and faster to run.

**Comment by lindareijnhoudt** [comment]
EASY-1018
